application: ty-wna
version: 1
runtime: python
api_version: 1

default_expiration: "5d"

builtins:
- datastore_admin: on
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/__init__.py
  login: admin

- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /static
  static_dir: application/static

- url: .*
  script: main.py
